name: Daily Connections Sync

on:
  schedule:
    - cron: '45 21 * * *'  # runs every day at 21:45 UTC
  workflow_dispatch: {}     # (keeps the “Run workflow” button)

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm i playwright@latest
          npx playwright install --with-deps chromium

      - name: Fetch latest puzzle and update files
        run: node scripts/fetch-cu.mjs

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update puzzle $(date -u +%F)" || echo "No changes"
          git push
