name: Daily Connections Sync (DRY RUN)

on:
  schedule:
    - cron: '2 23 * * *'   # 23:02 UTC daily (safe during dry-run; it won't modify files)
  workflow_dispatch: {}     # lets you run it manually from the Actions tab

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm i --no-audit --no-fund playwright@latest
          npx playwright install --with-deps chromium

      # 🔎 Debug run: logs all candidate/filtered tiles, does NOT write files
      - name: Fetch latest puzzle (dry-run: logs only)
        run: node scripts/fetch-cu.mjs --dump-buttons --dry-run

      # No-op during dry-run (kept for completeness)
      - name: Commit & push changes (no-op in dry-run)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: dry-run sync $(date -u +%F)" || echo "No changes"
          git push
