name: Connections Sync (DRY RUN)

on:
  schedule:
    - cron: '2 23 * * *'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run scraper (dry-run)
        run: npm i --no-save playwright@latest && npx playwright install --with-deps chromium && node scripts/fetch-cu.mjs --dump-buttons --dry-run
