name: Daily Connections Sync

on:
  schedule:
    - cron: '2 23 * * *'  # runs every day at 23:02 UTC
  workflow_dispatch: {}     # (keeps the “Run workflow” button)

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm i playwright@latest
          npx playwright install --with-deps chromium

      - name: Fetch latest puzzle and update files
        run: node scripts/fetch-cu.mjs

 - name: Fetch latest puzzle and update files
  run: node scripts/fetch-cu.mjs --dump-buttons --dry-run
  
